[[language]]
name = "rust"
# doesn't work, because cargo fmt doesn't support stdin formatting
# formatter = { command = "cargo", args = ["+nightly", "fmt"] }

[language-server.rust-analyzer.config.check]
command = "clippy"
